# Generated by Django 4.0.1 on 2022-01-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.FileField(upload_to='media/'),
        ),
    ]
