# Generated by Django 4.0.1 on 2022-01-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0003_alter_file_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
