# Generated by Django 4.0.1 on 2022-02-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0004_alter_file_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-date_upload']},
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('doc', 'Documents'), ('tb', 'Tables'), ('zip', 'Archives'), ('img', 'Images'), ('mp3', 'Audio'), ('avi', 'Video'), ('dr', 'Other')], default='dr', max_length=3, verbose_name='Type file'),
        ),
    ]
